Fix execution of marelle.
It looks like `swipl` may have change execution behaviour, as executing app as is was resulting in:

```
ERROR: Prolog initialisation failed:
ERROR: file `'meet'' does not exist
```

Not making `marelle.pl` a script (remove `-s`), and unquoting arguments seemed to solve the issue,
but would need to dig deeper to understand whether this is indeed to a change in `swipl` behaviour.